summaryIgnoreAbilities:
- leader
rangedSummaryAbilities:
- assault
- rapid fire
- heavy
- indirect fire
- ignores cover
- pistol
- lance
- anti
- precision
meleeSummaryAbilities:
- lance
- anti
- precision
summaryKeywords:
- fly
- vehicle
- monster
- infantry
- mounted
- battleline
- psyker
- markerlight
- transport
- dedicated transport
- character
- grenades
- smoke